### ISSUE TITLE
Profile comparison returns error: Profile not found

### ISSUE THREAD

**Issue by soledadescobar** [fundacion-sadosky/genis#108]
When you want to add a profile in the comparison page you get Profile not found error

**Comment by javieriserte** [comment]
Fixed in commit [891e7ca](https://github.com/fundacion-sadosky/genis/commit/891e7cafd06d9e96b684dcb3704778f4a061f6f4)

The problem was that the search API end point requires translate the json request body to a ProfileDataSearch object, however
in the frontend's searchProfileService sent a json object missing two fields, so the translation into a ProfileDataSearch was wrong.

Files affected in this fix:

- app/assets/javascripts/profiles/controllers/profileComparisonController.js
