### ISSUE TITLE
N Correction Error

### ISSUE THREAD

**Issue by soledadescobar** [fundacion-sadosky/genis#109]
When there is a match between one reference profile and an evidence with one contrubutor, after making the calculation scenario, in the results page you find "Number of individuals in the population of interest:". When you put a number to make the correction you get the error: [object Object]
[EjemploForenseUnico.txt](https://github.com/user-attachments/files/16131679/EjemploForenseUnico.txt)

**Comment by javieriserte** [comment]
Fixed in commit [554eb3e](https://github.com/fundacion-sadosky/genis/commit/554eb3e7477c292b82dec1657676dac708c0d32f)

![imagen](https://github.com/user-attachments/assets/3ac1fbef-f262-43f1-9b47-b4afe739cdf8)


There was two errors in this issue:

- The first one was while passing the lr value to the getNcorrection api end point where the lr value was as string instead of a number. Parsing the request object this this incorrect lr value lead to a Json ValidationError.
- The second problem was not showing correctly the error message from the Json ValidationError.

The files added / modified in this issue were:

- app/assets/javascripts/scenarios/controllers/resultsController.js
- app/assets/javascripts/scenarios/views/results.html
- app/controllers/Scenarios.scala
- conf/messages
- conf/routes
- app/util/JsValidationError.scala
