### ISSUE TITLE
Add category changes to traceability

### ISSUE THREAD

**Issue by soledadescobar** [fundacion-sadosky/genis#121]
When you change the category of a profile, add the information to the traceability and launch the matching process as happens when you register.

**Comment by javieriserte** [comment]
Fixed in commit [d32534e](https://github.com/fundacion-sadosky/genis/commit/d32534e29ab45d6dea22a6f399af94fb5da37eb1)

A few trace elements were added to the profiles in the lower and superior instance when a category modification occurs.

In inferior instance:

- A new trace telling about the category modification.

![image](https://github.com/user-attachments/assets/e39d5f2b-3ee3-4aab-a5cd-49ee05914285)

In the superior Instance:

- A new trace telling about the category modification in an inferior instance.

![image](https://github.com/user-attachments/assets/401e6384-bb45-427a-bd4b-5a44d3590ef0)

- A new trace telling about that a profile was imported from an inferior instance.

![image](https://github.com/user-attachments/assets/c7bcddc5-5802-4ed0-a87c-39ee5e8ef1ed)
