### ISSUE TITLE
More information to display when changing categories

### ISSUE THREAD

**Issue by soledadescobar** [fundacion-sadosky/genis#122]
Clarify in the replcation to superior instances, when going to the Approval of profiles from lower instances, clarify that it is a change of category
Add in the inbox that what is uploaded is with a change of category. Show if it is a new profile that is uploaded or if it is only the change of category.

**Comment by javieriserte** [comment]
This  is fixed in commit: [d32534e](https://github.com/fundacion-sadosky/genis/commit/d32534e29ab45d6dea22a6f399af94fb5da37eb1)

If a profile is sent from an inferior instance, now a message is shown telling the user that the profile sent had a category modification in the inferior instance.



![image](https://github.com/user-attachments/assets/04d50e4a-9210-4295-994e-27cb62852f2a)
